version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: A-level-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python main.py